namespace FamilieImport.Legacy.Models
{
    public class LegacyIR
    {
        public int ID { get; set; }
        public int IDIR { get; set; }
        public string Surname { get; set; }
        public string SoundsLike { get; set; }
        public string GivenName { get; set; }
        public string Prefix { get; set; }
        public string Title { get; set; }
        public string NameNote { get; set; }
        public int Gender { get; set; }
        public string BirthD { get; set; }
        public int BirthSD { get; set; }
        public int IDLRBirth { get; set; }
        public string ChrisD { get; set; }
        public int ChrisSD { get; set; }
        public int IDLRChris { get; set; }
        public string ChrTerm { get; set; }
        public string DeathD { get; set; }
        public int DeathSD { get; set; }
        public int IDLRDeath { get; set; }
        public string BuriedD { get; set; }
        public int BuriedSD { get; set; }
        public int IDLRBuried { get; set; }
        public int Cremated { get; set; }
        public int IDARBirth { get; set; }
        public int IDARChris { get; set; }
        public int IDARDeath { get; set; }
        public int IDARBuried { get; set; }
        public string BirthNote { get; set; }
        public string ChrisNote { get; set; }
        public string DeathNote { get; set; }
        public string BuriedNote { get; set; }
        public int Living { get; set; }
        public string BaptismD { get; set; }
        public int BaptismSD { get; set; }
        public int BaptismKind { get; set; }
        public int IDTRBaptism { get; set; }
        public string BaptismNote { get; set; }
        public int LDSB { get; set; }
        public string ConfirmationD { get; set; }
        public int ConfirmationSD { get; set; }
        public int ConfirmationKind { get; set; }
        public int IDTRConfirmation { get; set; }
        public string ConfirmationNote { get; set; }
        public int LDSC { get; set; }
        public string InitiatoryD { get; set; }
        public int InitiatorySD { get; set; }
        public int IDTRInitiatory { get; set; }
        public string InitiatoryNote { get; set; }
        public int LDSI { get; set; }
        public string EndowD { get; set; }
        public int EndowSD { get; set; }
        public int IDTREndow { get; set; }
        public string EndowNote { get; set; }
        public int LDSE { get; set; }
        public int TempleTag { get; set; }
        public int IDMRPref { get; set; }
        public int IDMRParents { get; set; }
        public int IDAR { get; set; }
        public int AncInterest { get; set; }
        public int DecInterest { get; set; }
        public int Tag1 { get; set; }
        public int Tag2 { get; set; }
        public int Tag3 { get; set; }
        public int Tag4 { get; set; }
        public int Tag5 { get; set; }
        public int Tag6 { get; set; }
        public int Tag7 { get; set; }
        public int Tag8 { get; set; }
        public int Tag9 { get; set; }
        public int TagGroup { get; set; }
        public int TagAnc { get; set; }
        public int TagDec { get; set; }
        public int SaveTag { get; set; }
        public int SrchTag { get; set; }
        public int qsTag { get; set; }
        public int ReminderTag { get; set; }
        public int ReminderTagDeath { get; set; }
        public int TreeNum { get; set; }
        public int LTMP1 { get; set; }
        public int LTMP2 { get; set; }
        public int AlreadyUsed { get; set; }
        public string UserRef { get; set; }
        public string AncestralRef { get; set; }
        public string Notes { get; set; }
        public string References { get; set; }
        public string Medical { get; set; }
        public string DeathCause { get; set; }
        public int PPCheck { get; set; }
        public int Imported { get; set; }
        public int Added { get; set; }
        public string AddedTime { get; set; }
        public int Updated { get; set; }
        public string UpdatedTime { get; set; }
        public string Relations { get; set; }
        public int NeverMarried { get; set; }
        public int DirectLine { get; set; }
        public string STMP1 { get; set; }
        public string IntelliShare { get; set; }
        public int Private { get; set; }
        public string PPExclude { get; set; }
        public int RGExclude { get; set; }
        public string DNA { get; set; }
        public int FSActive { get; set; }
        public int ColorTag1 { get; set; }
        public int ColorTag2 { get; set; }
    }
}
