namespace ImportLegacy.Legacy.Models
{
    public class LegacyMR
    {
        public int IDMR { get; set; }
        public int IDIRHusb { get; set; }
        public int HusbOrder { get; set; }
        public int HusbPrefMar { get; set; }
        public string HusbSurname { get; set; }
        public string HusbGivenName { get; set; }
        public string HusbMarrSurname { get; set; }
        public int HusbBirthSD { get; set; }
        public int IDIRWife { get; set; }
        public int WifeOrder { get; set; }
        public int WifePrefMar { get; set; }
        public string WifeSurname { get; set; }
        public string WifeGivenName { get; set; }
        public string WifeMarrSurname { get; set; }
        public int WifeBirthSD { get; set; }
        public int MarriedNameRule { get; set; }
        public int IDMS { get; set; }
        public string MarD { get; set; }
        public int MarSD { get; set; }
        public string MarEndD { get; set; }
        public int MarEndSD { get; set; }
        public int IDLRMar { get; set; }
        public string SealD { get; set; }
        public int SealSD { get; set; }
        public int IDTRSeal { get; set; }
        public string SealNote { get; set; }
        public int IDSS { get; set; }
        public int TempleTag { get; set; }
        public int Tag1 { get; set; }
        public int Tag2 { get; set; }
        public int Tag3 { get; set; }
        public int TagGroup { get; set; }
        public int SrchTag { get; set; }
        public int RemingerTag { get; set; }
        public int NotMarried { get; set; }
        public int NoChildren { get; set; }
        public int AlreadyUsed { get; set; }
        public int LTMP1 { get; set; }
        public int LTMP2 { get; set; }
        public string Notes { get; set; }
        public int PPCheck { get; set; }
        public int Added { get; set; }
        public string AddedTime { get; set; }
        public int Updated { get; set; }
        public string UpdatedTime { get; set; }
        public int IDAR { get; set; }
        public string HPhrase { get; set; }
        public string WPhrase { get; set; }
        public string RPhrase { get; set; }
        public string RPhrase2 { get; set; }
        public int ID { get; set; }
        public int Tag4 { get; set; }
        public int Tag5 { get; set; }
        public int Tag6 { get; set; }
        public int Tag7 { get; set; }
        public int Tag8 { get; set; }
        public int Tag9 { get; set; }
        public string UserRef { get; set; }
        public string MPhrase { get; set; }
        public string SPhrase { get; set; }
        public string HusbWifeOver1 { get; set; }
        public string HusbWifeOver2 { get; set; }
        public string WifeHusbOver1 { get; set; }
        public string WifeHusbOver2 { get; set; }
        public int Private { get; set; }
    }
}
